import HashMap from './HashMap.js';

HashMap().set('Girth', 'Wiedenbauer');
HashMap().set('Jonquil', 'Von Haggerston');
HashMap().set('Ben', 'Evolent');
HashMap().set('Phillip', 'Anthropy');
HashMap().set('Miles', 'Tone');
HashMap().set('Alan', 'Fresco');
HashMap().set('Hillary', 'Ousse');
HashMap().set('ela', 'First');
HashMap().set('ale', 'Second');
HashMap().set('Carlos', 'Old');
HashMap().set('Carlos', 'New');
console.log('\n===== BUCKETS =====');
console.log(HashMap().buckets);
console.log('\n===== LENGTH =====');
console.log(HashMap().length());
console.log('\n===== GET VALUE =====');

console.log(`\nThe value of the key Phillip: is: ${HashMap().get('Phillip')}`);
console.log('\n===== HAS KEY? =====');
console.log(`\nHas Phillip? ${HashMap().has('Phillip')}`);
console.log(`\nHas Alan? ${HashMap().has('Alan')}`);
console.log(`\nHas Jonq? ${HashMap().has('Jonq')}`);
console.log(`\nHas Miles? ${HashMap().has('Miles')}`);
console.log(`\nHas a void string? ${HashMap().has('')}`);
console.log(`\nHas ale? ${HashMap().has('ale')}`);
console.log('\n===== REMOVED =====');
console.log(`\nIs removed Jonquil? ${HashMap().remove('Jonquil')}`);
console.log(`\nIs removed ale? ${HashMap().remove('ale')}`);
console.log(`\nIs removed Phillip? ${HashMap().remove('Phillip')}`);
console.log(`\nIs removed Carlos? ${HashMap().remove('Carlos')}`);
console.log('\n===== BUCKETS AFTER REMOVES =====');
console.log(HashMap().buckets);
console.log('\n===== LENGTH =====');
console.log(HashMap().length());
console.log('\n===== KEYS =====');
console.log(HashMap().keys());
console.log('\n===== VALUES =====');
console.log(HashMap().values());
console.log('\n===== ENTRIES =====');
console.log(HashMap().entries());
HashMap().clear();
console.log('\n===== BUCKETS AFTER CLEAR =====');
console.log(HashMap().buckets);
console.log('\n===== LENGTH =====');
console.log(HashMap().length());
